adds: exception to throw when flysystem returns false
spatie/laravel-backup pull request #1348
Opened 2021-07-09 22:30 UTC by ajuchacko91

fix #1326 

I have done research on this and I would like to note it here.
league/flysystem - v1: Methods in League\Flysystem\FilesystemInterface doesn't throw exceptions instead returns true, false, resource, array. In flysystem v2 there are [exceptions which will be thrown](https://flysystem.thephpleague.com/v2/docs/usage/exception-handling/) instead of returning false.

In this package only Backup@delete checks for its result for rest of the methods(writeStream, readStream) I've added checking the result and throwing exception.

Even though I tried to add tests for these cases, I find it difficult to achieve

2021-07-12 07:57 UTC, freekmurze commented
Is this one ready for review?

2021-07-12 12:35 UTC, ajuchacko91 commented
sort of. 

I am trying to come up with a meaningful test case to document these change, 
I would like to give it a shot once more. need 2 more days.

I trying to figure out how to make a two tests where it should ```throw an exception while reading/stream or writing stream```.
Any thoughts on this would be helpful

thank you

2021-07-12 16:32 UTC, erikn69 commented
`$this->expectException(UnableToReadFile::class);`
Maybe it´s that
https://github.com/thephpleague/flysystem/blob/a3c694de9f7e844b76f9d1b61296ebf6e8d89d74/src/AdapterTestUtilities/FilesystemAdapterTestCase.php#L585-L592

2021-07-14 10:19 UTC, ajuchacko91 commented
Hi @erikn69,

that's not what I meant but thank you.

2021-07-14 10:19 UTC, ajuchacko91 commented
This PR is ready for review @freekmurze

2021-07-27 11:08 UTC, freekmurze requested changes
Looks good, only one minor nitpick

2021-07-27 14:21 UTC, ajuchacko91 commented
🤞

2021-07-29 07:49 UTC, merged

2021-07-29 07:49 UTC, freekmurze commented
Thanks!