Optimize storage and speed when making an encrypted backup
spatie/laravel-backup pull request #1825
Opened 2024-07-24 20:57 UTC by pellaras

**This PR addresses two issues:**

- There is a change of a backup to be stored as unencrypted, with no warning.
- The free disk space needed for an encrypted backup, is double of what  an unencrypted backup needs.

**In more detail:**

Using a Listener to wait for a successful creation of backup had the side effect of first creating a zip archive, unencrypted, then create the encrypted zip archive using the unencrypted one, which demanded double the available disk space, as well as more time.

Further to the above, and most concerning, is when the Listener fails to encrypt the zip file, it shows a warning about a notification failed to be sent, but it continues to store the archive on the destination disks, allowing for the unencrypted version to make it to a remote destination with possible privacy implications. A very likely scenario for this to happen, is when there is not enough disk space available for the encrypted backup to generated, but it does finish the unencrypted one.

This PR toggles the issue by setting the zip archive to use encryption as soon as the files are added, without the need of first making an unencrypted version on the temp folder. This also has a nice side-effect of needing the same available disk space as if no encryption was configured.

Happy to create a PR also for v9

Note: Tide-up the tests related to the encryption, as the Listener is no longer used.

2024-08-26 10:53 UTC, flexchar commented
LGTM! Would you be as kind to spare a few minutes on this one @freekmurze?:)

2024-08-26 11:41 UTC, freekmurze commented
Will do to, could you rebase against `main` to resolve the conflicts?

2024-09-12 13:17 UTC, pellaras commented
@freekmurze are you asking me? If yes, I can do a PR against main, after getting this merged under v8.

2024-09-13 12:06 UTC, Nielsvanpach commented
There are merge conflicts preventing this from being merged. You can rebase against the v8 branch.

2024-10-07 14:22 UTC, pellaras commented
@freekmurze rebased

2024-10-22 10:23 UTC, pellaras commented
Is there anything else that can be done to help merge this PR?

I am emphasizing the issue of having unencrypted archives make it to a remote storage (i.e. s3) under specific circumstances.

2024-12-23 14:00 UTC, freekmurze requested changes

2024-12-23 14:00 UTC, freekmurze commented on src/Tasks/Backup/BackupJob.php
> +        $this->sendNotification(new BackupZipWasCreated($pathToZip));
We should only send notifications if `$this->notifications` is set to `true`

2024-12-23 14:00 UTC, freekmurze commented on src/Tasks/Backup/Encryption.php
> +class Encryption
Rename this class to `BackupEncryptionConfig`

2024-12-23 14:00 UTC, freekmurze commented on src/Tasks/Backup/Zip.php
> +    public function loadEncryption()
Move all of this logic to a new static method `loadFromConfigFile` on the `BackupEncryptionClass` so the `Zip` becomes smaller

2025-04-24 08:37 UTC, freekmurze commented
Closing due to inactivity

2025-04-24 08:37 UTC, closed without merging