Allow overriding default implementation of TemporaryDirectory
spatie/laravel-backup pull request #1846
Opened 2024-09-29 22:00 UTC by jonerickson

This PR arises out of the need to change the default implementation of the `TemporaryDirectory` service. In our story, serving a multi-tenant application and using this package to backup each individual tenant's DB, we needed the ability to customize the temporary directory's location. Because we have a large number of tenants, we elected to create a batch job to backup each tenant's DB. Because of this, we are running into the issue where multiple jobs are trying to use the same temporary directory. As you can imagine, this creates chaos. We now have the ability to set the file path based on the tenant allowing each tenant to use their own temporary directory.

Because the package relies on Spatie's temporary directory package, we needed to create an adapter to extend the new `TemporaryDirectory` interface. This adapter just simply creates a new instance of `TemporaryDirectory` and then passes all calls to the default implementation.

With this PR, we can now do the following. This allows use to set the location in our own implementation's constructor.

```
$this->app->extend(TemporaryDirectory::class, function () {
    return new TenantTemporaryDirectory();
});
```

2024-10-24 05:32 UTC, jonerickson commented
Hey Spatie team, seeing if you have any questions regarding this PR. Thanks!

2025-01-06 14:57 UTC, freekmurze requested changes

2025-01-06 14:57 UTC, freekmurze commented on src/BackupServiceProvider.php
> +        $this->app->bind(TemporaryDirectoryContract::class, fn() => new TemporaryDirectoryAdapter(config('backup.temporary_directory') ?? storage_path('app/backup-temp')));
Added a contract and adapter feels a bit like overkill to me. Maybe just bind the `backup-temporary-project` string to a function that returns a new instance of temporary directory directly.

In your project you could just change the binding to whatever you want.

2025-01-10 02:33 UTC, jonerickson commented on src/BackupServiceProvider.php
> +        $this->app->bind(TemporaryDirectoryContract::class, fn() => new TemporaryDirectoryAdapter(config('backup.temporary_directory') ?? storage_path('app/backup-temp')));
Thanks for the feedback. I have removed both the contract and the adapter and just bound the implementation to a string.

2025-01-13 11:44 UTC, merged