Discord Notifications - Add limits in embed structures in discord notifications messages
spatie/laravel-backup pull request #1864
Opened 2024-12-31 17:44 UTC by mho22

Based on issue https://github.com/spatie/laravel-backup/issues/1819.

Reopened pull request from https://github.com/spatie/laravel-backup/pull/1834

@Nielsvanpach This is an initial pull request version. I may need further guidance to ensure it is ready for merging.

2025-01-02 08:40 UTC, Nielsvanpach requested changes
Thanks!

Could you add a test to verify if this works?

2025-01-02 08:40 UTC, Nielsvanpach commented on src/Notifications/Channels/Discord/DiscordMessage.php
> +                'value' => Str::limi($value, 1000),
```suggestion
                'value' => Str::limit($value, 1000),
```

2025-01-03 15:28 UTC, mho22 commented on src/Notifications/Channels/Discord/DiscordMessage.php
> +                'value' => Str::limi($value, 1000),
sorry about that...

2025-01-03 15:29 UTC, mho22 commented
@Nielsvanpach I added a `DiscordMessageTest.php` in `tests/Notifications/Channels/Discord` directory to match the modifications I made into the DiscordMessage.php file regarding embed limits. Let me know if something is missing.

2025-01-06 09:19 UTC, merged